package com.liyiwei.basethirdlib.dbgreendao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liyiwei.basethirdlib.dbgreendao.bean.DownloadInfo;
import com.liyiwei.basethirdlib.dbgreendao.bean.ExamCache;
import com.liyiwei.basethirdlib.dbgreendao.bean.ExamPaperConfig;
import com.liyiwei.basethirdlib.dbgreendao.bean.MessageLabel;
import com.liyiwei.basethirdlib.dbgreendao.bean.SearchHistory;
import com.liyiwei.basethirdlib.dbgreendao.bean.SubDownloadInfo;
import com.liyiwei.basethirdlib.dbgreendao.bean.VideoConfig;
import com.liyiwei.basethirdlib.dbgreendao.bean.VideoConfigHistory;

import com.liyiwei.basethirdlib.dbgreendao.greendao.DownloadInfoDao;
import com.liyiwei.basethirdlib.dbgreendao.greendao.ExamCacheDao;
import com.liyiwei.basethirdlib.dbgreendao.greendao.ExamPaperConfigDao;
import com.liyiwei.basethirdlib.dbgreendao.greendao.MessageLabelDao;
import com.liyiwei.basethirdlib.dbgreendao.greendao.SearchHistoryDao;
import com.liyiwei.basethirdlib.dbgreendao.greendao.SubDownloadInfoDao;
import com.liyiwei.basethirdlib.dbgreendao.greendao.VideoConfigDao;
import com.liyiwei.basethirdlib.dbgreendao.greendao.VideoConfigHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadInfoDaoConfig;
    private final DaoConfig examCacheDaoConfig;
    private final DaoConfig examPaperConfigDaoConfig;
    private final DaoConfig messageLabelDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig subDownloadInfoDaoConfig;
    private final DaoConfig videoConfigDaoConfig;
    private final DaoConfig videoConfigHistoryDaoConfig;

    private final DownloadInfoDao downloadInfoDao;
    private final ExamCacheDao examCacheDao;
    private final ExamPaperConfigDao examPaperConfigDao;
    private final MessageLabelDao messageLabelDao;
    private final SearchHistoryDao searchHistoryDao;
    private final SubDownloadInfoDao subDownloadInfoDao;
    private final VideoConfigDao videoConfigDao;
    private final VideoConfigHistoryDao videoConfigHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadInfoDaoConfig = daoConfigMap.get(DownloadInfoDao.class).clone();
        downloadInfoDaoConfig.initIdentityScope(type);

        examCacheDaoConfig = daoConfigMap.get(ExamCacheDao.class).clone();
        examCacheDaoConfig.initIdentityScope(type);

        examPaperConfigDaoConfig = daoConfigMap.get(ExamPaperConfigDao.class).clone();
        examPaperConfigDaoConfig.initIdentityScope(type);

        messageLabelDaoConfig = daoConfigMap.get(MessageLabelDao.class).clone();
        messageLabelDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        subDownloadInfoDaoConfig = daoConfigMap.get(SubDownloadInfoDao.class).clone();
        subDownloadInfoDaoConfig.initIdentityScope(type);

        videoConfigDaoConfig = daoConfigMap.get(VideoConfigDao.class).clone();
        videoConfigDaoConfig.initIdentityScope(type);

        videoConfigHistoryDaoConfig = daoConfigMap.get(VideoConfigHistoryDao.class).clone();
        videoConfigHistoryDaoConfig.initIdentityScope(type);

        downloadInfoDao = new DownloadInfoDao(downloadInfoDaoConfig, this);
        examCacheDao = new ExamCacheDao(examCacheDaoConfig, this);
        examPaperConfigDao = new ExamPaperConfigDao(examPaperConfigDaoConfig, this);
        messageLabelDao = new MessageLabelDao(messageLabelDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        subDownloadInfoDao = new SubDownloadInfoDao(subDownloadInfoDaoConfig, this);
        videoConfigDao = new VideoConfigDao(videoConfigDaoConfig, this);
        videoConfigHistoryDao = new VideoConfigHistoryDao(videoConfigHistoryDaoConfig, this);

        registerDao(DownloadInfo.class, downloadInfoDao);
        registerDao(ExamCache.class, examCacheDao);
        registerDao(ExamPaperConfig.class, examPaperConfigDao);
        registerDao(MessageLabel.class, messageLabelDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(SubDownloadInfo.class, subDownloadInfoDao);
        registerDao(VideoConfig.class, videoConfigDao);
        registerDao(VideoConfigHistory.class, videoConfigHistoryDao);
    }
    
    public void clear() {
        downloadInfoDaoConfig.clearIdentityScope();
        examCacheDaoConfig.clearIdentityScope();
        examPaperConfigDaoConfig.clearIdentityScope();
        messageLabelDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        subDownloadInfoDaoConfig.clearIdentityScope();
        videoConfigDaoConfig.clearIdentityScope();
        videoConfigHistoryDaoConfig.clearIdentityScope();
    }

    public DownloadInfoDao getDownloadInfoDao() {
        return downloadInfoDao;
    }

    public ExamCacheDao getExamCacheDao() {
        return examCacheDao;
    }

    public ExamPaperConfigDao getExamPaperConfigDao() {
        return examPaperConfigDao;
    }

    public MessageLabelDao getMessageLabelDao() {
        return messageLabelDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public SubDownloadInfoDao getSubDownloadInfoDao() {
        return subDownloadInfoDao;
    }

    public VideoConfigDao getVideoConfigDao() {
        return videoConfigDao;
    }

    public VideoConfigHistoryDao getVideoConfigHistoryDao() {
        return videoConfigHistoryDao;
    }

}
